server:
  port: 8200

spring:
  application:
    name: account-service
  redis:
    database: 0
  datasource:
    dynamic:
      primary: account
      strict: false
      datasource:
        account:
          url: jdbc:mysql:///music_cloud_drive_account
          username: root
          password: plf,.123
        secret_key:
          url: jdbc:mysql:///music_cloud_drive_secret_key
          username: root
          password: plf,.123
