server:
  port: 8084

spring:
  application:
    name: gateway-service
  datasource:
    url: jdbc:mysql:///music_cloud_drive_secret_key
    username: root
    password: plf,.123
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: account-api
          uri: lb://account-service
          predicates:
            - Path=/account/**
        - id: resource-api
          uri: lb://resource-service
          predicates:
            - Path=/file/** ,/get/**
        - id: core-api
          uri: lb://core-service
          predicates:
            - Path=/sheet/** ,/user/**
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'